name: smlss_server
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.12
  - pytorch::pytorch=2.0.1
  - torchaudio=2.0.2
  - flask
  - transformers
  - lame
  - pip
  - numba

  - pip:
      - git+ssh://git@github.com/facebookresearch/SimulEval.git
      - git+ssh://git@github.com/fairinternal/fairseq-py.git@seamless_main
      - git+https://github.com/openai/whisper.git
      - git+https://github.com/jianfch/stable-ts.git
      - psola==0.0.1
      - silero==0.4.1
      - flask-sockets==0.2.1
      - google-cloud-media-translation==0.11.3
      - g2p_en

      # - hydra-core==1.3.2

      # - importlib-metadata==6.0.0
      # - importlib-resources==5.12.0
      # - lazy-loader==0.1
      # - lit==15.0.7
      # - msgpack==1.0.5

      # - soxr==0.3.4
      # - triton==2.0.0
      # - zipp==3.15.0
